# build using "docker build ./ -t $ARTIFACT_NAME --build-arg VERSION=1.2.3.4"
FROM mcr.microsoft.com/openjdk/jdk:17-mariner as runtime

ARG VERSION_ARG
ARG ARTIFACT_NAME

ENV VERSION=$VERSION_ARG
ENV ARTIFACT_NAME=$ARTIFACT_NAME

WORKDIR /

COPY ./${ARTIFACT_NAME}-${VERSION_ARG}.jar /${ARTIFACT_NAME}-${VERSION_ARG}.jar
COPY ./ai.jar /ai.jar

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-javaagent:/ai.jar","-jar","/${ARTIFACT_NAME}-${VERSION_ARG}.jar"]