name: 00-Init-Repository-Utils

on:
  workflow_call:
  workflow_dispatch:

jobs:
    pets-utils-01-zipkin:
        uses: ./.github/workflows/79-continuous-integration-utils-01-zipkin.yml
        secrets: inherit
    pets-utils-02-prometheus:
        needs: pets-utils-01-zipkin
        uses: ./.github/workflows/79-continuous-integration-utils-02-prometheus.yml
        secrets: inherit
    pets-utils-03-grafana:
        needs: pets-utils-02-prometheus
        uses: ./.github/workflows/79-continuous-integration-utils-03-grafana.yml
        secrets: inherit